name: Deploy via SSH

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Bun
        uses: oven-sh/setup-bun@v1

      - name: Install frontend dependencies
        run: bun install
        working-directory: ./front-end

      - name: Build frontend application
        run: bun run build
        working-directory: ./front-end

      - name: Prepare backend for deployment
        run: |
          mkdir -p back-end/public
          cp -r front-end/dist/* back-end/public/

      - name: Copy files to server via SCP
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          password: ${{ secrets.SSH_PASSWORD }}
          source: '.'
          target: '~/htdocs/exploring.swit.vn.ua'

      - name: Install dependencies and restart server
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          password: ${{ secrets.SSH_PASSWORD }}
          script: |
            cd ~/htdocs/exploring.swit.vn.ua
            bun install -g pm2
            bun install --production
            pm2 restart index.ts || pm2 start index.ts --name contact-book-app
